name: 'Check for broken links'

on:
  push:
    branches: 
      - 'gh-pages'
  workflow_dispatch:

jobs:
  check-links:
    name: 'Check all files for broken links'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
    - name: 'Grant execute permission for check-links.sh'
      run: chmod +x .github/scripts/check-links.sh
    - name: 'Execute the script'
      shell: '/bin/bash {0}'
      run: .github/scripts/check-links.sh docs
