name: 'Check for broken links'

on:
  push:
    branches: 
      - 'gh-pages'

jobs:
  check-links:
    name: 'Check all files for broken links'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Grant execute permission for check-links.sh'
      run: chmod +x .github/scripts/check-links.sh
    - name: 'Execute the script'
      run: .github/scripts/check-links.sh docs
