name: Label ready prs

on:
  pull_request:
    types:
      - unlabeled

jobs:
  move_prs:
    if: github.event.label.name == 'resolved'
    runs-on: ubuntu-latest

    steps:
    - name: Move to the PR-READY column
      uses: alex-page/github-project-automation-plus@v0.7.1
      with:
        project: LiSA
        column: PR-READY
        repo-token: ${{ secrets.SSVPAT }}
    - name: Create missing milestone comment
      if: ${{ github.event.milestone == null }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.number }}
        body: |
          This pr has been marked as resolved but no milestone
          is set. Link it to an existing milestone or create a new one.